[package]
name = "rupamix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
pulse = {version = "2.28.1", package = "libpulse-binding"}
